import { z } from 'zod';
import { isoDateTimeSchema, uuidSchema } from './common.schema.js';
import { skillImportanceSchema } from './job.schema.js';

/** Scores are integers 0–100 everywhere. A float score implies a precision the
 *  rubric does not have. */
export const scoreSchema = z.number().int().min(0).max(100);

// ─── ATS (deterministic, no AI) ───────────────────────────────────────────────

export const RULE_STATUSES = ['PASS', 'PARTIAL', 'FAIL', 'NOT_APPLICABLE'] as const;
export const ruleStatusSchema = z.enum(RULE_STATUSES);

/** Every lost point is traceable to a named rule with a human explanation.
 *  That traceability is the entire credibility argument for the score. */
export const atsRuleResultSchema = z.object({
  id: z.string(),
  label: z.string(),
  status: ruleStatusSchema,
  weight: z.number().min(0),
  earned: z.number().min(0),
  explanation: z.string(),
  fix: z.string().optional(),
});
export type AtsRuleResult = z.infer<typeof atsRuleResultSchema>;

export const ATS_COMPONENTS = [
  'parseability',
  'keywords',
  'formatting',
  'readability',
  'completeness',
] as const;
export const atsComponentSchema = z.enum(ATS_COMPONENTS);
export type AtsComponent = z.infer<typeof atsComponentSchema>;

export const atsComponentScoreSchema = z.object({
  score: scoreSchema,
  weight: z.number().min(0).max(1),
});

export const atsScoreSchema = z.object({
  score: scoreSchema,
  rubricVersion: z.number().int().positive(),
  components: z.record(atsComponentSchema, atsComponentScoreSchema),
  rules: z.array(atsRuleResultSchema),
});
export type AtsScore = z.infer<typeof atsScoreSchema>;

// ─── Match (deterministic composite over embeddings) ──────────────────────────

export const matchComponentSchema = z.object({
  score: scoreSchema,
  weight: z.number().min(0).max(1),
});

export const matchBreakdownSchema = z.object({
  skills: matchComponentSchema.extend({
    matched: z.array(z.string()),
    missing: z.array(z.string()),
  }),
  experience: matchComponentSchema.extend({
    requiredYears: z.number().nullable(),
    detectedYears: z.number().nullable(),
  }),
  projects: matchComponentSchema.extend({
    relevant: z.array(z.string()),
  }),
  education: matchComponentSchema,
});
export type MatchBreakdown = z.infer<typeof matchBreakdownSchema>;

export const missingSkillSchema = z.object({
  skill: z.string(),
  importance: skillImportanceSchema,
  weight: z.number().min(0).max(1),
  /** How to acquire or evidence it. Generated by the AI layer, grounded in the
   *  gap the deterministic engine already computed. */
  suggestion: z.string(),
});
export type MissingSkill = z.infer<typeof missingSkillSchema>;

// ─── Recommendations ──────────────────────────────────────────────────────────

export const RECOMMENDATION_TYPES = [
  'BULLET_REWRITE',
  'ADD_SKILL',
  'ADD_SECTION',
  'ADD_PROJECT',
  'FORMATTING',
  'QUANTIFY',
  'SUMMARY_REWRITE',
] as const;
export const recommendationTypeSchema = z.enum(RECOMMENDATION_TYPES);

export const SEVERITIES = ['HIGH', 'MEDIUM', 'LOW'] as const;
export const severitySchema = z.enum(SEVERITIES);

export const recommendationSchema = z.object({
  id: z.string(),
  type: recommendationTypeSchema,
  severity: severitySchema,
  message: z.string(),
  /** JSON Pointer into the resume document, so the client can scroll to and
   *  highlight the exact field this refers to. RFC 6901. */
  targetPath: z.string().nullable(),
});
export type Recommendation = z.infer<typeof recommendationSchema>;

// ─── AI proposals ─────────────────────────────────────────────────────────────

/**
 * Every write-capable AI feature returns a proposal, never a silent edit.
 *
 * `placeholders` is the honesty mechanism: the model cannot know the user's real
 * numbers, so any figure it introduces is listed here and the UI blocks Accept
 * until each one is confirmed or corrected. docs/11 §5.
 */
export const aiProposalSchema = z.object({
  id: z.string(),
  before: z.string().nullable(),
  after: z.string(),
  rationale: z.string(),
  confidence: z.number().min(0).max(1),
  placeholders: z.array(z.string()),
});
export type AiProposal = z.infer<typeof aiProposalSchema>;

export const bulletOptimizeSchema = z.object({
  bullets: z
    .array(z.object({ id: z.string(), text: z.string().trim().min(1).max(500) }))
    .min(1)
    .max(10),
  context: z
    .object({
      role: z.string().max(120).optional(),
      jobDescriptionId: uuidSchema.optional(),
    })
    .optional(),
});
export type BulletOptimizeInput = z.infer<typeof bulletOptimizeSchema>;

export const proposalsResponseSchema = z.object({
  proposals: z.array(aiProposalSchema),
  quotaRemaining: z.number().int().min(0),
});

// ─── Analysis result ──────────────────────────────────────────────────────────

export const createAnalysisSchema = z.object({
  resumeId: uuidSchema,
  /** Absent = ATS-only analysis with no JD to match against. */
  jobDescriptionId: uuidSchema.optional(),
});
export type CreateAnalysisInput = z.infer<typeof createAnalysisSchema>;

export const analysisResultSchema = z.object({
  id: uuidSchema,
  resumeVersionId: uuidSchema,
  jobDescriptionId: uuidSchema.nullable(),
  atsScore: scoreSchema,
  matchScore: scoreSchema.nullable(),
  rubricVersion: z.number().int().positive(),
  breakdown: matchBreakdownSchema.nullable(),
  missingSkills: z.array(missingSkillSchema),
  recommendations: z.array(recommendationSchema),
  createdAt: isoDateTimeSchema,
});
export type AnalysisResult = z.infer<typeof analysisResultSchema>;
